name: material3_drawer
description: Material 3 Navigation Drawer component.
version: 1.0.0
homepage: https://github.com/danielgorka/material3_drawer

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  badges: ^2.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
